(function (root) {
  "use strict";
  // Store absolute UTC instants. PDT launch announcements are UTC-7, not a fixed year-round Pacific offset.
  const releaseNotes = "https://www.nexon.com/maplestory/news/general/45621/founder-s-access-release-notes";
  const saleAnnouncement = "https://www.nexon.com/maplestory/news/sale/44134/classic-world-founder-s-packages-now-on-sale";
  const gmRestrictions = "Talk to Paul at Lith Harbor to enter. You cannot participate while holding a Scroll of Secrets or if you participated in a GM event within the past 24 hours.";
  const gmSchedules = [
    {
      id: "physical-fitness",
      title: "Physical Fitness Challenge",
      shortTitle: "Physical Fitness",
      days: [7, 14],
      hour: "00",
      description: "Complete the jump quest within 15 minutes to earn a Scroll of Secrets. Movement and jump are set to default; Haste, Teleport, and consumable effects are disabled.",
      note: gmRestrictions,
    },
    {
      id: "coconut-harvest",
      title: "Coconut Harvest",
      days: [12],
      hour: "00",
      description: "Join one of two teams and harvest coconuts with melee attacks within five minutes. The winning team earns a Scroll of Secrets. Ranged attacks and skills are disabled; Harry sells a melee weapon in the event map if you need one.",
      note: gmRestrictions,
    },
    {
      id: "up-and-up",
      title: "Up and Up",
      days: [9, 19],
      hour: "00",
      description: "Climb through three stages and choose the correct portals before time runs out. Reach the final stage to earn a Scroll of Secrets. Movement and jump are set to default; Haste, Teleport, and consumable effects are disabled.",
      note: gmRestrictions,
    },
    {
      id: "monster-invasion",
      title: "Monster Invasion",
      days: [11, 16, 20],
      hour: "01",
      description: "Join other Maplers as GMs summon monsters in towns. Defeat Mano, King Slime, Mushmom, Zombie Mushmom, and Jr. Balrog for a chance at rewards including mesos, Event Trophies, Scrolls of Secrets, and Elixirs.",
      note: "Death penalties do not apply while in a town. Reward pools vary by monster; see the official release notes.",
    },
  ];
  const events = [
    {
      id: "founders-access",
      title: "Founder’s Access",
      shortTitle: "Founder’s Access",
      category: "launch",
      start: "2026-10-06T18:00:00Z",
      description: "Your Classic World adventure starts here. Founder’s Access opens ahead of the public Grand Launch. Check the official FAQ for access requirements and the latest launch information.",
      originalTime: "Tuesday, October 6, 2026 · 11:00 AM PDT (UTC−7)",
      source: "https://www.nexon.com/maplestory/news/general/45385/maple-story-classic-world-faq",
      note: "This entry marks the server opening, not a daily recurring event.",
    },
    {
      id: "grand-launch",
      title: "Classic World Grand Launch",
      shortTitle: "Grand Launch",
      category: "launch",
      start: "2026-10-21T18:00:00Z",
      description: "A new chapter in a familiar world. MapleStory Classic World’s public Grand Launch opens on October 21. Visit the official FAQ for launch details and any schedule changes.",
      originalTime: "Wednesday, October 21, 2026 · 11:00 AM PDT (UTC−7)",
      source: "https://www.nexon.com/maplestory/news/general/45385/maple-story-classic-world-faq",
      note: "The calendar converts the announced instant into your selected timezone, including daylight saving time.",
    },
    {
      id: "founders-package-claim",
      title: "Founder’s Package claim deadline",
      shortTitle: "Package claim deadline",
      category: "event",
      kind: "deadline",
      start: "2026-11-30T23:59:00Z",
      description: "Claim your Founder’s Package items from your in-game mailbox before the announced deadline. Packages are claimable from the start of Founder’s Access. Each account can claim once per platform: once on the Nexon website and once on Steam.",
      originalTime: "Monday, November 30, 2026 · 11:59 PM UTC",
      source: saleAnnouncement,
      note: "You must leave Maple Island before opening the package. After claiming it, you have 30 days to open it; that personal deadline depends on when you claim and is not a fixed calendar date.",
    },
    {
      id: "founders-first-step",
      title: "Founder’s First Step",
      shortTitle: "Founder’s First Step",
      category: "event",
      start: "2026-10-06T18:00:00Z",
      end: "2026-10-20T23:59:00Z",
      description: "Characters Lv. 10 and above can accept the [Event] Founder’s First Step quest from Maple Administrator. Check in daily for cumulative rewards: Day 1 includes 5,000 Leaf Points, megaphones, atmospheric effect boxes, and potions; Days 2–7 include 1,000 Leaf Points and potions; Days 8–14 include megaphones and an atmospheric effect box.",
      originalTime: "October 6, 2026 · 6:00 PM UTC – October 20, 2026 · 11:59 PM UTC",
      source: releaseNotes,
      note: "Rewards can be claimed once per account for each check-in day. Missed days do not reset your cumulative check-in count. No daily reset time is specified in these release notes.",
    },
    ...gmSchedules.flatMap((schedule) => schedule.days.map((day) => ({
      id: `${schedule.id}-oct-${day}`,
      title: schedule.title,
      shortTitle: schedule.shortTitle || schedule.title,
      category: "event",
      start: `2026-10-${String(day).padStart(2, "0")}T${schedule.hour}:00:00Z`,
      end: `2026-10-${String(day).padStart(2, "0")}T02:00:00Z`,
      description: schedule.description,
      originalTime: `October ${day}, 2026 · ${schedule.hour === "00" ? "12:00 AM" : "1:00 AM"} – 2:00 AM UTC`,
      source: releaseNotes,
      note: schedule.note,
    }))),
    {
      id: "founders-package-sales",
      title: "Founder’s Package sales end",
      shortTitle: "Package sales end",
      category: "event",
      kind: "deadline",
      start: "2026-10-15T06:59:00Z",
      description: "Purchase or upgrade your Founder’s Package on the Nexon website or Steam by the announced deadline. Snail costs US$29.99 and does not include early access; Orange Mushroom costs US$59.99 and Zakum costs US$79.99, and both include Founder’s Access. Package items are cosmetic and grant no stats or bonuses.",
      originalTime: "October 14, 2026 · 11:59 PM PDT (UTC−7)",
      source: saleAnnouncement,
      note: "Upgrades are available during the sale by paying the price difference. This is the purchase/upgrade deadline, not the November 30 mailbox claim deadline. Prices reflect the official USD shop catalog at the time this calendar was updated.",
    },
    {
      id: "mark-of-beta",
      title: "Mark of Beta — planned opening",
      shortTitle: "Mark of Beta (planned)",
      category: "event",
      start: "2026-10-21T18:00:00Z",
      description: "The Mark of Beta event is planned to begin at Grand Launch on October 21, 2026.",
      originalTime: "At Grand Launch · October 21, 2026 (11:00 AM PDT per the launch FAQ)",
      source: releaseNotes,
      note: "This is a planned opening milestone, not a confirmed event duration. The release notes do not specify a separate opening time, end date, or participation details.",
    },
    {
      id: "classic-beginnings-rewards",
      title: "Classic Beginnings rewards available",
      shortTitle: "Classic Beginnings rewards",
      category: "event",
      start: "2026-10-21T18:00:00Z",
      description: "Accounts that completed [Event] A Strange and Familiar Wood and [Event] Beyond the Unknown during Closed Online Tests #1 and #2 can claim the Classic Beginnings Label/Chat Ring at Grand Launch.",
      originalTime: "At Grand Launch · October 21, 2026 (11:00 AM PDT per the launch FAQ)",
      source: releaseNotes,
      note: "This entry marks claim availability for eligible test accounts. No claim deadline or separate opening time is specified in these release notes.",
    },
    {
      id: "founders-package-sale-window",
      title: "Founder’s Package sale",
      shortTitle: "Founder’s Package sale",
      category: "event",
      kind: "sale",
      start: "2026-09-01T18:00:00Z",
      end: "2026-10-15T07:00:00Z",
      description: "Purchase or upgrade a Snail, Orange Mushroom, or Zakum Founder’s Package. Orange Mushroom and Zakum include Founder’s Access on October 6; Snail does not. All package items are cosmetic and usable by male and female characters of all jobs.",
      originalTime: "Official shop window: September 1, 2026 · 18:00 UTC – October 15, 2026 · 07:00 UTC (exclusive cutoff). Announcement deadline: October 14 · 11:59 PM PDT.",
      source: saleAnnouncement,
      timingSource: "https://www.nexon.com/api/maplestory/founders-pack/v1/no-auth/packs",
      note: "Exact start and exclusive cutoff come from the public Classic World shop data, not the article publication date. The final announced purchase minute is 11:59 PM PDT on October 14. Snail: US$29.99; Orange Mushroom: US$59.99; Zakum: US$79.99. Prices may vary by currency or change.",
    },
    {
      id: "signature-style-sale",
      title: "Signature Style (Frieren collaboration) sale",
      shortTitle: "Signature Style (Frieren collaboration) sale",
      category: "event",
      kind: "sale",
      start: "2026-09-09T18:00:00Z",
      end: "2026-10-08T00:00:00Z",
      description: "The limited-time Frieren: Beyond Journey’s End collaboration offers outfit packages including hair and face styles. Outfit themes include Frieren (standard, Ringlets, and Sleep), Fern, Stark, Übel, Himmel, Aura, Lügner, and Linie. Buy with NX on the Classic World Founder’s Package page: one collection costs 7,900 NX, or ten cost 79,000 NX. Items are delivered to your Classic World account during Grand Launch.",
      originalTime: "Official Classic World shop window: September 9, 2026 · 18:00 UTC – October 8, 2026 · 00:00 UTC (exclusive cutoff; October 7 · 5:00 PM PDT).",
      source: saleAnnouncement,
      timingSource: "https://www.nexon.com/api/maplestory/founders-pack/v1/no-auth/frieren/event",
      detailsSource: "https://www.nexon.com/maplestory/news/sale/44291/signature-style-collection",
      note: "The announcement says available until October 7; exact sale instants come from the Classic-specific public shop data. Pick up items after leaving Maple Island from October 23 through November 3 at 11:59 PM UTC. Coupons and resulting items are not tradable in Classic World. The linked outfit article also covers regular MapleStory; its item duration and exchange rules are not assumed to apply to Classic World.",
    },
    {
      id: "signature-style-claim",
      title: "Signature Style Collection pickup deadline",
      shortTitle: "Signature Style pickup ends",
      category: "event",
      kind: "deadline",
      start: "2026-11-03T23:59:00Z",
      description: "Pick up your purchased Signature Style Collection items from your Classic World in-game mailbox after leaving Maple Island. The announced pickup period is October 23 through November 3 at 11:59 PM UTC. Items will no longer be available for pickup after that deadline.",
      originalTime: "November 3, 2026 · 11:59 PM UTC. Pickup begins October 23; no opening hour is specified.",
      source: saleAnnouncement,
      note: "Grand Launch delivery and mailbox pickup are separate: delivery is during Grand Launch, but the stated pickup period begins October 23. No precise October 23 opening time is invented. Signature Style Collection coupons and resulting items cannot be traded.",
    },
    {
      id: "signature-style-delivery",
      title: "Signature Style automatic delivery",
      shortTitle: "Signature Style delivery",
      category: "event",
      start: "2026-10-21T18:00:00Z",
      description: "Purchased Signature Style Collection items are delivered automatically to your Classic World account during Grand Launch. Delivery does not mean immediate pickup: mailbox pickup begins October 23, after you leave Maple Island.",
      originalTime: "During Grand Launch · October 21, 2026 (launch opens at 11:00 AM PDT).",
      source: saleAnnouncement,
      note: "This is a Grand Launch delivery milestone, not a separately announced exact processing time. Signature Style Collection coupons and resulting items cannot be traded in Classic World.",
    },
    {
      id: "signature-style-pickup-window",
      title: "Signature Style Collection pickup window",
      shortTitle: "Signature Style pickup",
      category: "event",
      kind: "claim-window",
      startDate: "2026-10-23",
      end: "2026-11-03T23:59:00Z",
      description: "After leaving Maple Island, pick up your purchased Signature Style Collection items from your Classic World in-game mailbox during the announced October 23–November 3 pickup period. Items are delivered automatically during Grand Launch, but pickup is a separate window.",
      originalTime: "October 23, 2026 (opening hour not specified) – November 3, 2026 · 11:59 PM UTC.",
      source: saleAnnouncement,
      note: "Items will no longer be available for pickup after November 3 at 11:59 PM UTC. Signature Style Collection coupons and resulting items cannot be traded in Classic World. The opening date stays October 23 as announced; only the precise cutoff is converted to your timezone.",
    },
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = events;
  else root.MAPLE_EVENTS = events;
})(globalThis);
